#!/bin/bash
set -euo pipefail
# Generates dnsmasq config from the user's exclude-domains.txt
# Writes to /etc/dnsmasq.d/vpn-cdn-bypass.conf

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
DOMAIN_FILE="${HOME}/.config/vpn-split/exclude-domains.txt"
DNSMASQ_CONF="/etc/dnsmasq.d/vpn-cdn-bypass.conf"

if [ ! -f "$DOMAIN_FILE" ]; then
    echo "Error: $DOMAIN_FILE not found" >&2
    echo "Create it from the example: cp exclude-domains.example.txt ~/.config/vpn-split/exclude-domains.txt" >&2
    exit 1
fi

echo "# Auto-generated by vpn-gen-config — do not edit manually" > /tmp/vpn-cdn-bypass.conf
echo "# Source: $DOMAIN_FILE" >> /tmp/vpn-cdn-bypass.conf
echo "# Generated: $(date)" >> /tmp/vpn-cdn-bypass.conf
echo "" >> /tmp/vpn-cdn-bypass.conf

while IFS= read -r line; do
    # Skip comments and empty lines
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// /}" ]] && continue

    domain=$(echo "$line" | xargs)  # trim whitespace
    echo "nftset=/${domain}/4#ip#vpn_split#cdn_bypass" >> /tmp/vpn-cdn-bypass.conf
    echo "nftset=/${domain}/6#ip6#vpn_split#cdn_bypass6" >> /tmp/vpn-cdn-bypass.conf
done < "$DOMAIN_FILE"

sudo mv /tmp/vpn-cdn-bypass.conf "$DNSMASQ_CONF"

count=$(grep -c "^nftset=" "$DNSMASQ_CONF" 2>/dev/null || echo 0)
echo "Generated $DNSMASQ_CONF with $((count / 2)) domain rules"
echo "Run: sudo systemctl restart dnsmasq"
