#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

source "$SCRIPT_DIR/../common/log.sh"

# Pi needs node >= 22.19, but .zshrc.init pins the shell to $NVM_DIR/alias/default
# (v20 on this machine) — and `npm -g` installs are PER NODE VERSION. So we can't
# just use whatever npm is on PATH: install under the active node and the shell
# never sees the binary; install under the default and it fails pi's engine floor.
# Pick the newest installed nvm node that clears the floor, and pin to it.
NODE_BIN=""
for _dir in "$HOME"/.nvm/versions/node/v*/; do
	[ -x "${_dir}bin/npm" ] || continue
	_ver=${_dir%/}
	_ver=${_ver##*/v}
	_maj=${_ver%%.*}
	_min=${_ver#*.}
	_min=${_min%%.*}
	if [ "$_maj" -gt 22 ] || { [ "$_maj" -eq 22 ] && [ "$_min" -ge 19 ]; }; then
		[ -n "$NODE_BIN" ] && [ "$(printf '%s\n%s\n' "$_ver" "$NODE_VER" | sort -V | tail -1)" = "$NODE_VER" ] && continue
		NODE_BIN="${_dir}bin"
		NODE_VER="$_ver"
	fi
done

if [ -z "$NODE_BIN" ]; then
	fail "no installed node >= 22.19 found under \$HOME/.nvm — run the node setup script (or \`nvm install 24\`) first, then re-run this script."
fi

step "Using node v$NODE_VER for pi ($NODE_BIN)"
export PATH="$NODE_BIN:$PATH"

if [ -x "$NODE_BIN/pi" ]; then
	debug "Pi is already installed under node v$NODE_VER, skipping installation..."
else
	# ponytail: gated on the binary's absence because pi.dev's installer opens
	# /dev/tty directly and draws an arrow-key install/reinstall/uninstall menu
	# whenever a terminal exists — `< /dev/null` does NOT suppress it (same trap
	# as `wt create` in CLAUDE.md). The gate means that menu appears at most once,
	# on first install; with no tty (agent/CI) the installer proceeds on its own.
	# If it ever needs to be fully unattended, swap for:
	#   npm install -g @earendil-works/pi-coding-agent
	info "Installing Pi..."
	curl -fsSL https://pi.dev/install.sh | sh
	success "Pi installation completed!"
fi

# npm's bin shim is `#!/usr/bin/env node`, so running it from a shell on the
# default (v20) node would still fail pi's engine floor. This launcher lives on
# the shell's PATH and pins BOTH the binary and its node, so `pi` works no matter
# which nvm version is active.
mkdir -p "$HOME/.local/bin"
cat >"$HOME/.local/bin/pi" <<EOF
#!/bin/sh
# Generated by dotfiles script/pi/setup.sh — do not edit.
PATH="$NODE_BIN:\$PATH" exec "$NODE_BIN/pi" "\$@"
EOF
chmod +x "$HOME/.local/bin/pi"
success "Linked pi launcher at \$HOME/.local/bin/pi (node v$NODE_VER)"
