require("items.widgets.battery")
require("items.widgets.wifi")
require("items.widgets.brightness")
require("items.widgets.volume")
require("items.widgets.temp")
require("items.widgets.memory")
require("items.widgets.cpu")
