#!/bin/bash
#===============================================================================
# sync.sh — snapshot your user-installed Brave extensions back into the repo.
#
# Mirror of claude-settings-sync: reads the LIVE browser and rewrites the
# tracked configs/brave/extensions.txt (union of Web Store extensions across all
# local profiles). setup.sh's soft installer replays that list via Brave's
# "External Extensions" mechanism, so re-running this after you add/remove an
# extension keeps the dotfiles in sync with what you actually run.
#
# Safe while Brave is open: it only reads profile prefs, writes to the repo.
#===============================================================================
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$SCRIPT_DIR/../common/log.sh"
REPO_DIR=$(cd -- "$SCRIPT_DIR/../.." &>/dev/null && pwd)

case "$OSTYPE" in
	darwin*) BRAVE_DIR="$HOME/Library/Application Support/BraveSoftware/Brave-Browser" ;;
	*) BRAVE_DIR="$HOME/.config/BraveSoftware/Brave-Browser" ;;
esac
[ -d "$BRAVE_DIR" ] || fail "Brave profile dir not found: $BRAVE_DIR"

DEST="$REPO_DIR/configs/brave/extensions.txt"
tmp=$(mktemp)
{
	echo "# Brave extensions — GENERATED by script/brave/sync.sh (run: brave-sync)."
	echo "# Union of your Web Store extensions across all local Brave profiles."
	echo "# setup.sh soft-installs each via 'External Extensions' (user-removable,"
	echo "# no managed policy). Re-run 'brave-sync' after adding/removing extensions."
	python3 "$SCRIPT_DIR/extract_extensions.py" "$BRAVE_DIR"
} >"$tmp"
mv "$tmp" "$DEST"

count=$(grep -cvE '^[[:space:]]*(#|$)' "$DEST" || true)
success "Wrote $count extension(s) → configs/brave/extensions.txt"

# Snapshot enabled brave://flags too (soft, same source-of-truth idea).
FLAGS_DEST="$REPO_DIR/configs/brave/flags.txt"
ftmp=$(mktemp)
{
	echo "# brave://flags experiments to enable — one per line, e.g. https-by-default@2."
	echo "# SOFT + ADDITIVE: unioned into Local State's enabled_labs_experiments (never"
	echo "# disables flags you enabled yourself); turn any off at brave://flags anytime."
	echo "# GENERATED by brave-sync. Applied while Brave is CLOSED (run: brave-theme)."
	python3 -c "import json,sys;print('\n'.join(json.load(open(sys.argv[1])).get('browser',{}).get('enabled_labs_experiments') or []))" "$BRAVE_DIR/Local State"
} >"$ftmp"
mv "$ftmp" "$FLAGS_DEST"
fcount=$(grep -cvE '^[[:space:]]*(#|$)' "$FLAGS_DEST" || true)
success "Wrote $fcount flag(s) → configs/brave/flags.txt"

# Snapshot the curated allowlist of soft UI/feature/content prefs from the
# canonical (first) profile. Only allowlisted keys that exist are captured.
PREFS_DEST="$REPO_DIR/configs/brave/prefs.txt"
CANON=$(python3 -c "import json;o=json.load(open('$BRAVE_DIR/Local State')).get('profile',{}).get('profiles_order') or ['Default'];print(o[0])")
ptmp=$(mktemp)
{
	echo "# Soft Brave prefs (UI / New Tab Page / Brave features / content defaults),"
	echo "# applied to ALL profiles by brave-theme (Brave must be CLOSED). GENERATED by"
	echo "# brave-sync from the '$CANON' profile — only curated allowlisted keys, never"
	echo "# bookmarks/passwords/history/site-exceptions. Edit values freely; # comments ok."
	python3 "$SCRIPT_DIR/brave_prefs.py" snapshot "$BRAVE_DIR/$CANON/Preferences"
} >"$ptmp"
mv "$ptmp" "$PREFS_DEST"
pcount=$(grep -cvE '^[[:space:]]*(#|$)' "$PREFS_DEST" || true)
success "Wrote $pcount pref(s) → configs/brave/prefs.txt"
info "Review: git -C \"$REPO_DIR\" diff configs/brave/"
