#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

source "$SCRIPT_DIR/../common/log.sh"
source "$SCRIPT_DIR/../common/symlink.sh"

# Install Claude Code CLI if not present
if ! command -v claude &>/dev/null; then
	step "Installing Claude Code"
	curl -fsSL https://claude.ai/install.sh | bash
else
	debug "Claude Code already installed"
fi

debug "Ensuring $HOME/.claude exists"
mkdir -p "$HOME/.claude"

# Ensure source config directories exist before symlinking
mkdir -p "$SCRIPT_DIR/../../configs/claude/"{agents,commands,prompts}

link_file "$SCRIPT_DIR/../../configs/claude/agents/" "$HOME/.claude/agents" "directory"
link_file "$SCRIPT_DIR/../../configs/claude/commands/" "$HOME/.claude/commands" "directory"
link_file "$SCRIPT_DIR/../../configs/claude/prompts/" "$HOME/.claude/prompts" "directory"
# NOTE: ~/.claude/skills is intentionally NOT a whole-dir symlink — skills are
# projected per-skill (work-only gating) by script/skills/setup.sh below.
# A whole-dir link here would make per-skill links resolve INTO the repo.
link_file "$SCRIPT_DIR/../../configs/claude/statusline.sh" "$HOME/.claude/statusline.sh"

# settings.json comes from a DEDICATED per-environment file (no base/overlay
# merge): configs/claude/settings.work.json or settings.personal.json, each a
# COMPLETE settings file. The active one is copied verbatim to ~/.claude (not
# symlinked, so the app can write runtime keys like model/effortLevel without
# touching the repo). That dedicated file is the single source of truth — run
# `claude-settings-sync` (script/claude/sync-settings.sh) to capture live edits
# back into it BEFORE re-running this script, or they'll be overwritten.
if [[ "${WORK_ENV:-}" == "1" || "${DOT_ENVIRONMENT:-}" == "work" ]]; then
	SETTINGS_SRC="$SCRIPT_DIR/../../configs/claude/settings.work.json"
else
	SETTINGS_SRC="$SCRIPT_DIR/../../configs/claude/settings.personal.json"
fi
SETTINGS_TARGET="$HOME/.claude/settings.json"
[ -L "$SETTINGS_TARGET" ] && rm "$SETTINGS_TARGET"  # drop legacy symlink layout
cp "$SETTINGS_SRC" "$SETTINGS_TARGET"
success "Installed $SETTINGS_TARGET ($(basename "$SETTINGS_SRC"))"

# CLAUDE.md is GENERATED (shared base + work/personal overlay), mirroring the
# settings.json approach above, so work-only instructions never follow personal
# machines around. The final ~/.claude/CLAUDE.md is what Claude actually reads,
# so it must keep that name (not a symlink to an overlay). A hidden marker line
# (`<!-- @dot-overlay:<env> -->`) is inserted between base and overlay so live
# edits to ~/.claude/CLAUDE.md can be split back into the repo sources via
# script/claude/sync-claude.sh (the `claude-sync` shell alias).
CLAUDE_BASE="$SCRIPT_DIR/../../configs/claude/CLAUDE.md"
if [[ "${WORK_ENV:-}" == "1" || "${DOT_ENVIRONMENT:-}" == "work" ]]; then
	CLAUDE_ENV="work"
else
	CLAUDE_ENV="personal"
fi
CLAUDE_OVERLAY="$SCRIPT_DIR/../../configs/claude/CLAUDE.${CLAUDE_ENV}.md"
CLAUDE_TARGET="$HOME/.claude/CLAUDE.md"
# Legacy layout symlinked this to the repo file; replace with a generated file.
[ -L "$CLAUDE_TARGET" ] && rm "$CLAUDE_TARGET"
{
	cat "$CLAUDE_BASE"
	printf '\n<!-- @dot-overlay:%s --><!-- generated by script/claude/setup.sh; edit base/overlay in the repo, or edit here and run claude-sync -->\n\n' "$CLAUDE_ENV"
	[ -f "$CLAUDE_OVERLAY" ] && cat "$CLAUDE_OVERLAY"
} >"${CLAUDE_TARGET}.tmp" && mv "${CLAUDE_TARGET}.tmp" "$CLAUDE_TARGET"
success "Generated $CLAUDE_TARGET (CLAUDE.${CLAUDE_ENV}.md overlay)"

link_file "$SCRIPT_DIR/../../configs/claude/hooks/" "$HOME/.claude/hooks"
# cmux sidebar hook scripts (workspace title, PR-approval pill, task progress bar)
link_file "$SCRIPT_DIR/../../configs/claude/scripts/" "$HOME/.claude/scripts" "directory"

# Touch ID command gate (macOS): build BioPrompt.app — the SwiftUI approval
# dialog used by the touchid-gate.py PreToolUse hook to biometric-gate
# sensitive Bash commands. ~/.local/bin/bioprompt is a shim that execs the
# bundled binary (running it at its bundle path is what gives it app identity
# in the system auth UI).
if [[ "$OSTYPE" == darwin* ]] && command -v swiftc &>/dev/null; then
	BIOPROMPT_SRC="$SCRIPT_DIR/../../configs/claude/hooks/bioprompt.swift"
	BIOPROMPT_PLIST="$SCRIPT_DIR/../../configs/claude/hooks/bioprompt-Info.plist"
	BIOPROMPT_APP="$HOME/Applications/BioPrompt.app"
	BIOPROMPT_BIN="$BIOPROMPT_APP/Contents/MacOS/bioprompt"
	BIOPROMPT_SHIM="$HOME/.local/bin/bioprompt"
	if [[ ! -x "$BIOPROMPT_BIN" || "$BIOPROMPT_SRC" -nt "$BIOPROMPT_BIN" || "$BIOPROMPT_PLIST" -nt "$BIOPROMPT_APP/Contents/Info.plist" ]]; then
		step "Building BioPrompt.app (Touch ID helper)..."
		mkdir -p "$BIOPROMPT_APP/Contents/MacOS" "$(dirname "$BIOPROMPT_SHIM")"
		cp "$BIOPROMPT_PLIST" "$BIOPROMPT_APP/Contents/Info.plist"
		swiftc -O "$BIOPROMPT_SRC" -o "$BIOPROMPT_BIN"
		printf '#!/bin/sh\nexec "%s" "$@"\n' "$BIOPROMPT_BIN" >"$BIOPROMPT_SHIM"
		chmod +x "$BIOPROMPT_SHIM"
		success "BioPrompt.app built at $BIOPROMPT_APP (shim: $BIOPROMPT_SHIM)"
	else
		debug "BioPrompt.app already built and up to date. Skipping."
	fi
fi

# Skills live in configs/skills and are projected into each agent CLI.
source "$SCRIPT_DIR/../skills/setup.sh"

# Make nvm-installed node available — this script runs as its own process,
# so it doesn't inherit nvm from the node component's shell.
# (nvm.sh is incompatible with `set -eu`, so relax around the source)
if ! command -v npm &>/dev/null && [ -s "$HOME/.nvm/nvm.sh" ]; then
	set +eu
	export NVM_DIR="$HOME/.nvm"
	\. "$NVM_DIR/nvm.sh"
	set -eu
fi

# Install TypeScript language server for Claude Code's typescript-lsp plugin
if ! command -v typescript-language-server &>/dev/null; then
	if command -v npm &>/dev/null; then
		info "Installing typescript-language-server..."
		npm install -g typescript-language-server typescript
		success "typescript-language-server installed."
	else
		info "npm not found — skipping typescript-language-server install. Run 'npm install -g typescript-language-server typescript' manually after installing Node.js."
	fi
else
	debug "typescript-language-server already installed. Skipping."
fi
