#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
REPO_DIR=$(cd -- "$SCRIPT_DIR/../.." &>/dev/null && pwd)

source "$SCRIPT_DIR/../common/log.sh"
source "$SCRIPT_DIR/../common/symlink.sh"
source "$SCRIPT_DIR/../common/dot_env.sh"
source "$SCRIPT_DIR/../common/bioprompt.sh"

# Resolve the environment ONCE for everything below: settings.json, CLAUDE.md,
# and the sourced skills/setup.sh (which reads the exports this sets). See
# script/common/dot_env.sh for the precedence rules and why the .dotconfig
# fallback is load-bearing for standalone runs.
dot_export_env
debug "Claude environment: $DOT_ENV"

# Install Claude Code CLI if not present
if ! command -v claude &>/dev/null; then
	step "Installing Claude Code"
	curl -fsSL https://claude.ai/install.sh | bash
else
	debug "Claude Code already installed"
fi

debug "Ensuring $HOME/.claude exists"
mkdir -p "$HOME/.claude"

# Ensure source config directories exist before symlinking
mkdir -p "$SCRIPT_DIR/../../configs/claude/"{agents,commands,prompts,themes}

link_file "$SCRIPT_DIR/../../configs/claude/agents/" "$HOME/.claude/agents" "directory"
link_file "$SCRIPT_DIR/../../configs/claude/commands/" "$HOME/.claude/commands" "directory"
link_file "$SCRIPT_DIR/../../configs/claude/prompts/" "$HOME/.claude/prompts" "directory"
# Custom themes: each themes/<slug>.json registers as `custom:<slug>` — the SLUG
# IS THE FILENAME, not the "name" field. Select via /theme or by setting
# "theme": "custom:<slug>" in settings.{work,personal}.json.
link_file "$SCRIPT_DIR/../../configs/claude/themes/" "$HOME/.claude/themes" "directory"
# NOTE: ~/.claude/skills is intentionally NOT a whole-dir symlink — skills are
# projected per-skill (work-only gating) by script/skills/setup.sh below.
# A whole-dir link here would make per-skill links resolve INTO the repo.
link_file "$SCRIPT_DIR/../../configs/claude/statusline.sh" "$HOME/.claude/statusline.sh"

# settings.json comes from a DEDICATED per-environment file (no base/overlay
# merge): configs/claude/settings.work.json or settings.personal.json, each a
# COMPLETE settings file. The active one is copied verbatim to ~/.claude (not
# symlinked, so the app can write runtime keys like model/effortLevel without
# touching the repo). That dedicated file is the single source of truth — run
# `claude-settings-sync` (script/claude/sync-settings.sh) to capture live edits
# back into it BEFORE re-running this script, or they'll be overwritten.
SETTINGS_SRC="$REPO_DIR/configs/claude/settings.${DOT_ENV}.json"
SETTINGS_TARGET="$HOME/.claude/settings.json"
[ -L "$SETTINGS_TARGET" ] && rm "$SETTINGS_TARGET"  # drop legacy symlink layout
cp "$SETTINGS_SRC" "$SETTINGS_TARGET"
success "Installed $SETTINGS_TARGET ($(basename "$SETTINGS_SRC"))"

# CLAUDE.md is GENERATED (shared base + work/personal overlay), mirroring the
# settings.json approach above, so work-only instructions never follow personal
# machines around. The final ~/.claude/CLAUDE.md is what Claude actually reads,
# so it must keep that name (not a symlink to an overlay). A hidden marker line
# (`<!-- @dot-overlay:<env> -->`) is inserted between base and overlay so live
# edits to ~/.claude/CLAUDE.md can be split back into the repo sources via
# script/claude/sync-claude.sh (the `claude-sync` shell alias).
CLAUDE_BASE="$REPO_DIR/configs/claude/CLAUDE.md"
CLAUDE_ENV="$DOT_ENV"
CLAUDE_OVERLAY="$REPO_DIR/configs/claude/CLAUDE.${CLAUDE_ENV}.md"
CLAUDE_TARGET="$HOME/.claude/CLAUDE.md"
# Legacy layout symlinked this to the repo file; replace with a generated file.
[ -L "$CLAUDE_TARGET" ] && rm "$CLAUDE_TARGET"
{
	cat "$CLAUDE_BASE"
	printf '\n<!-- @dot-overlay:%s --><!-- generated by script/claude/setup.sh; edit base/overlay in the repo, or edit here and run claude-sync -->\n\n' "$CLAUDE_ENV"
	# if/fi, not `[ ] && cat`: as the group's LAST command a false test makes the
	# whole group exit 1, so the `&& mv` below silently doesn't run — leaving a
	# stale CLAUDE.md plus an orphan .tmp while still printing success.
	if [ -f "$CLAUDE_OVERLAY" ]; then cat "$CLAUDE_OVERLAY"; fi
} >"${CLAUDE_TARGET}.tmp" && mv "${CLAUDE_TARGET}.tmp" "$CLAUDE_TARGET"
success "Generated $CLAUDE_TARGET (CLAUDE.${CLAUDE_ENV}.md overlay)"

link_file "$SCRIPT_DIR/../../configs/claude/hooks/" "$HOME/.claude/hooks"

# Touch ID command gate (macOS): build BioPrompt.app — the SwiftUI approval
# dialog used by the touchid-gate.py PreToolUse hook to biometric-gate
# sensitive Bash commands. Shared with Codex (see script/common/bioprompt.sh);
# ~/.local/bin/bioprompt is a shim that execs the bundled binary (running it at
# its bundle path is what gives it app identity in the system auth UI).
build_bioprompt

# Skills live in configs/skills and are projected into each agent CLI.
source "$SCRIPT_DIR/../skills/setup.sh"

# Make nvm-installed node available — this script runs as its own process,
# so it doesn't inherit nvm from the node component's shell.
# (nvm.sh is incompatible with `set -eu`, so relax around the source)
if ! command -v npm &>/dev/null && [ -s "$HOME/.nvm/nvm.sh" ]; then
	set +eu
	export NVM_DIR="$HOME/.nvm"
	\. "$NVM_DIR/nvm.sh"
	set -eu
fi

# Install TypeScript language server for Claude Code's typescript-lsp plugin
if ! command -v typescript-language-server &>/dev/null; then
	if command -v npm &>/dev/null; then
		info "Installing typescript-language-server..."
		npm install -g typescript-language-server typescript
		success "typescript-language-server installed."
	else
		info "npm not found — skipping typescript-language-server install. Run 'npm install -g typescript-language-server typescript' manually after installing Node.js."
	fi
else
	debug "typescript-language-server already installed. Skipping."
fi
