#!/bin/bash
#===============================================================================
# sync-claude.sh — reverse of the CLAUDE.md generation in setup.sh.
#
# setup.sh generates ~/.claude/CLAUDE.md by concatenating the shared base
# (configs/claude/CLAUDE.md) with the active work/personal overlay, joined by a
# hidden marker line:  <!-- @dot-overlay:<env> -->
#
# This script reads that generated file, splits it at the marker, and writes the
# two halves BACK into the repo sources — so you can edit ~/.claude/CLAUDE.md
# live (that's the file Claude reads) and persist the changes into version
# control. The marker tells us which overlay (work|personal) to write.
#
# Round-trips cleanly: sync-back then re-run setup.sh reproduces the same file.
#===============================================================================

set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$SCRIPT_DIR/../common/log.sh"

TARGET="${1:-$HOME/.claude/CLAUDE.md}"
BASE_SRC="$SCRIPT_DIR/../../configs/claude/CLAUDE.md"

[ -f "$TARGET" ] || fail "No generated CLAUDE.md at $TARGET"
if [ -L "$TARGET" ]; then
	fail "$TARGET is still a symlink (legacy layout). Run script/claude/setup.sh first to generate it."
fi

# Locate the marker and the env it names.
marker=$(grep -nE '<!-- @dot-overlay:[a-z]+' "$TARGET" | head -1 || true)
[ -n "$marker" ] || fail "No '<!-- @dot-overlay:<env> -->' marker in $TARGET — was it generated by setup.sh?"
env_name=$(printf '%s' "$marker" | sed -nE 's/.*@dot-overlay:([a-z]+).*/\1/p')
[ -n "$env_name" ] || fail "Could not parse env from marker: $marker"
OVERLAY_SRC="$SCRIPT_DIR/../../configs/claude/CLAUDE.${env_name}.md"

step "Syncing $TARGET → base + ${env_name} overlay"

# Split at the marker. Everything before → base; everything after → overlay.
# Trim the blank padding lines the generator inserts around the marker so the
# round-trip is stable (no creeping blank lines on repeated syncs).
awk -v out_base="$BASE_SRC" -v out_ovl="$OVERLAY_SRC" '
	/<!-- @dot-overlay:/ && !seen { seen=1; next }
	!seen { base[++b] = $0; next }
	      { ovl[++o]  = $0 }
	END {
		while (b > 0 && base[b] ~ /^[ \t]*$/) b--
		for (i = 1; i <= b; i++) print base[i] > out_base
		s = 1; while (s <= o && ovl[s] ~ /^[ \t]*$/) s++
		while (o >= s && ovl[o] ~ /^[ \t]*$/) o--
		for (i = s; i <= o; i++) print ovl[i] > out_ovl
	}
' "$TARGET"

success "Wrote $(basename "$BASE_SRC") and $(basename "$OVERLAY_SRC")"
info "Review with: git -C \"$SCRIPT_DIR/../..\" diff configs/claude/"
