add_newline = true
command_timeout = 500
format = "$username$hostname$directory$git_branch$git_status$character"

[username]
show_always = false
format = "[$user]($style)@"
style_user = "bold yellow"
style_root = "bold red"

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "bold yellow"

[directory]
truncation_length = 1
truncate_to_repo = false
format = "[$path]($style)"
style = "bold cyan"

[git_branch]
format = " [$branch]($style)"
style = "cyan"

[character]
error_symbol = " [✗](bold cyan)"
success_symbol = " [❯](bold cyan)"

[git_status]
format = '[$all_status]($style)'
style = "cyan"
ahead = " ⇡${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
behind = " ⇣${count}"
conflicted = " "
up_to_date = ""
untracked = "?"
modified = " "
stashed = ""
staged = ""
renamed = ""
deleted = ""
