
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here
# See https://wiki.hyprland.org/Configuring for more information

exec-once = sleep 1 && sunshine 
exec-once = sleep 2 && liquidctl --pick 1 initialize
exec-once = sleep 3 && liquidctl --pick 1 set "sync" speed 50 
#exec-once = sleep 4 && hyde-shell waybar
# --- Portal Configuration for File Chooser / Steam ---

# 1. Start the wlr-specific backend
# This is crucial for Hyprland's Wayland file dialogs.
exec-once = /usr/lib/xdg-desktop-portal-wlr &

# 2. Start the core portal service
# Note: You might need a small delay here if the core service fails to start
# cleanly or picks the wrong backend too soon, but this usually works.
exec-once = sleep 1 && /usr/lib/xdg-desktop-portal & 

bind = $mainMod SHIFT, F1, exec, ~/scripts/screenON.sh
bind = $mainMod SHIFT, F2, exec, ~/scripts/screenOFF.sh
bind = $mainMod SHIFT, F3, exec, ~/scripts/headless_screenOFF.sh

# for obs
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_DESKTOP_PORTAL,gtk 
env = XDG_DESKTOP_PORTAL,hyprland 

# // █ █▄░█ █▀█ █░█ ▀█▀
# // █ █░▀█ █▀▀ █▄█ ░█░


#  Uncomment to enable // change to a preferred value
# 🔗 See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    #follow_mouse = 2 
    sensitivity = 0.2
    force_no_accel = 0
    accel_profile = flat 

    # 🔗 See https://wiki.hyprland.org/Configuring/Variables/#touchpad
    touchpad {
        natural_scroll = no
    }
    
}

# device {
#     name = mouse-passthrough 
#     enabled = false
# }

# 🔗 See https://wiki .hyprland.org/Configuring/Variables/#gestures
gestures {
#     workspace_swipe = true
#     workspace_swipe_fingers = 3
}


# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    gaps_in = 5
    gaps_out = 10

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 6

    # Fix washed-out appearance: make focused windows fully opaque
    active_opacity = 1.0
    inactive_opacity = 0.90
    fullscreen_opacity = 1.0
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
