customCommands:
  - key: c
    context: "localBranches"
    description: Create pull request
    command: gh pr create --web --draft
  - key: "n"
    context: "localBranches"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        key: "BranchType"
        options:
          - name: "feature"
            description: "a feature branch"
            value: "feature"
          - name: "hotfix"
            description: "a hotfix branch"
            value: "hotfix"
          - name: "release"
            description: "a release branch"
            value: "release"
      - type: "input"
        title: "What is the new branch name or ticket?"
        key: "BranchName"
        initialValue: ""
    command: "git checkout -b {{.Form.BranchType}}/{{.Form.BranchName}}"
gui:
  theme:
    activeBorderColor:
      - "#f5a97f"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#f5a97f"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
  authorColors:
    "*": "#b7bdf8"

  showRandomTip: false
  showNumstatInFilesView: true
  nerdFontsVersion: "3"
