# Full effects profile for AMD dGPU — animations and blur enabled
animations {
    enabled = yes, please :)
}

decoration {
    blur {
        enabled = true
    }

    shadow {
        enabled = true
    }
}
